export const POKEMON_LIST = [
  { name: 'Pikachu', type: 'ELECTRIC', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png' },
  { name: 'Raichu', type: 'ELECTRIC', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png' },
  { name: 'Charizard', type: 'FIRE', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png' },
  { name: 'Blastoise', type: 'WATER', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png' },
  { name: 'Venusaur', type: 'GRASS', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png' },
  { name: 'Squirtle', type: 'WATER', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png' },
  { name: 'Charmander', type: 'FIRE', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png' },
  { name: 'Bulbasaur', type: 'GRASS', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png' },
  { name: 'Wartortle', type: 'WATER', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png' },
  { name: 'Charmeleon', type: 'FIRE', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png' },
  { name: 'Ivysaur', type: 'GRASS', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png' },
  { name: 'Gengar', type: 'GHOST', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png' },
  { name: 'Dragonite', type: 'DRAGON', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png' },
  { name: 'Mewtwo', type: 'PSYCHIC', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png' },
  { name: 'Snorlax', type: 'NORMAL', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png' },
  { name: 'Machamp', type: 'FIGHTING', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png' },
  { name: 'Gyarados', type: 'WATER', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png' },
  { name: 'Alakazam', type: 'PSYCHIC', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png' },
  { name: 'Arcanine', type: 'FIRE', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png' },
  { name: 'Jolteon', type: 'ELECTRIC', image_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png' }
] as const;

export const POKEMON_SKILLS = [
  { name: 'Thunderbolt', type: 'ELECTRIC', damage: 10, is_attack: true },
  { name: 'Thunder', type: 'ELECTRIC', damage: 10, is_attack: true },
  { name: 'Thunder Wave', type: 'ELECTRIC', damage: 10, is_attack: false },
  { name: 'Electric Shield', type: 'ELECTRIC', damage: 10, is_attack: false },
  { name: 'Flamethrower', type: 'FIRE', damage: 10, is_attack: true },
  { name: 'Fire Blast', type: 'FIRE', damage: 10, is_attack: true },
  { name: 'Will-O-Wisp', type: 'FIRE', damage: 10, is_attack: false },
  { name: 'Flame Guard', type: 'FIRE', damage: 10, is_attack: false },
  { name: 'Hydro Pump', type: 'WATER', damage: 10, is_attack: true },
  { name: 'Surf', type: 'WATER', damage: 10, is_attack: true },
  { name: 'Aqua Ring', type: 'WATER', damage: 10, is_attack: false },
  { name: 'Water Veil', type: 'WATER', damage: 10, is_attack: false },
  { name: 'Solar Beam', type: 'GRASS', damage: 10, is_attack: true },
  { name: 'Leaf Blade', type: 'GRASS', damage: 10, is_attack: true },
  { name: 'Leech Seed', type: 'GRASS', damage: 10, is_attack: false },
  { name: 'Synthesis', type: 'GRASS', damage: 10, is_attack: false },
  { name: 'Shadow Ball', type: 'GHOST', damage: 10, is_attack: true },
  { name: 'Shadow Claw', type: 'GHOST', damage: 10, is_attack: true },
  { name: 'Confuse Ray', type: 'GHOST', damage: 10, is_attack: false },
  { name: 'Phantom Force', type: 'GHOST', damage: 10, is_attack: false },
  { name: 'Dragon Claw', type: 'DRAGON', damage: 10, is_attack: true },
  { name: 'Outrage', type: 'DRAGON', damage: 10, is_attack: true },
  { name: 'Dragon Dance', type: 'DRAGON', damage: 10, is_attack: false },
  { name: 'Dragon Scale', type: 'DRAGON', damage: 10, is_attack: false },
  { name: 'Psychic', type: 'PSYCHIC', damage: 10, is_attack: true },
  { name: 'Psybeam', type: 'PSYCHIC', damage: 10, is_attack: true },
  { name: 'Calm Mind', type: 'PSYCHIC', damage: 10, is_attack: false },
  { name: 'Barrier', type: 'PSYCHIC', damage: 10, is_attack: false },
  { name: 'Body Slam', type: 'NORMAL', damage: 10, is_attack: true },
  { name: 'Hyper Beam', type: 'NORMAL', damage: 10, is_attack: true },
  { name: 'Rest', type: 'NORMAL', damage: 10, is_attack: false },
  { name: 'Protect', type: 'NORMAL', damage: 10, is_attack: false },
  { name: 'Dynamic Punch', type: 'FIGHTING', damage: 10, is_attack: true },
  { name: 'Close Combat', type: 'FIGHTING', damage: 10, is_attack: true },
  { name: 'Bulk Up', type: 'FIGHTING', damage: 10, is_attack: false },
  { name: 'Counter', type: 'FIGHTING', damage: 10, is_attack: false }
] as const;

export const TOURNAMENT_VENUES = [
  'Cerulean City Gym',
  'Viridian City Gym',
  'Indigo Plateau',
  'Battle Frontier Arena',
  'Lumiose City Stadium'
] as const;